version: "3"

services:
  ### Bancos
  gerente-db:
    networks:
      - gerente
    container_name: gerente-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
        - ./bantads-gerente/init.sql:/docker-entrypoint-initdb.d/init.sql
  # cliente-db:
  #   # networks: 
  #   #   - cliente
  #   container_name: cliente-db
  #   image: postgres:15.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5433:5433"
  #   volumes:
  #       - ./bantads-cliente/init.sql:/docker-entrypoint-initdb.d/init.sql
  # auth-db:
  #   # networks:
  #   #   - auth
  #   container_name: auth-db
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_INITDB_DATABASE=auth-db
  #     - MONGO_INITDB_ROOT_USERNAME=bantads
  #     - MONGO_INITDB_ROOT_PASSWORD=bantads
  #   volumes:
  #       - ./bantads-autenticacao/init.js:/docker-entrypoint-initdb.d/init.js
  pgadmin:
    # networks:
    #   - auth
    #   - cliente
    #   - gerente
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bantads@bantads.br
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    restart: unless-stopped
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=auth-db
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=bantads
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=bantads
  #   ports:
  #     - 8081:8081
  #   restart: always
  
  ### RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    networks:
      - gerente
      - orquestrador
    image: rabbitmq:3.11.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  ### Aplicações
  orquestrador:
    networks:
      - gerente
      - orquestrador
    image: "orquestrador:latest"
    build:
      context: ./bantads-orquestrador
    container_name: bantads-orquestrador
    ports:
      - "5005:8080"
    volumes:
      - ./bantads-orquestrador/:/app
  gerente:
    container_name: gerente
    networks:
      - gerente
    image: "gerente:latest"
    build:
      context: ./bantads-gerente
    volumes:
      - ./bantads-gerente/:/app
    depends_on:
      - gerente-db
    ports:
      - "5004:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://gerente-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  gateway:
    container_name: gateway
    networks:
      - gerente
    image: "gateway:latest"
    build:
      context: ./bantads-gateway
      # dockerfile: Dockerfile
    volumes:
      - ./bantads-gateway/:/app
      - /app/node_modules
    ports:
      - "5000:5000"

## Networks
networks:
  orquestrador:
    driver: bridge
  gerente:
    driver: bridge