version: "3"

services:
  ### Bancos
  gerente-db:
    container_name: gerente-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cliente-db:
    container_name: cliente-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  auth-db:
    container_name: auth-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bantads
      - MONGO_INITDB_ROOT_PASSWORD=bantads
  
  ### RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
  